### ISSUE TITLE
UX: display all sections without having to click them

### ISSUE THREAD

**Issue by akivajgordon** [binyamin/bentcher#1]
Cool project! I love the beautiful typography and lack of other fluff – it's simple.

I experienced frustration when having to open the sections. I would have loved it even more if all the sections were already opened. I don't see much value in having them closed off. I think the section titles are enough to anchor me so that I don't get lost, and I can't imagine myself feeling the need to "declutter" by closing off sections. It also makes the page jump too much when it opens, so it's disorienting to me.

Just my thoughts, but like I said, I think this is cool!

**Comment by binyamin** [comment]
Thanks for the love. Funnily enough, I used the only hebrew, serif, variable font that I could find on NPM. I guess it's a winner!

I hear what you're saying about the sections. I do think there's value in collapsing _zimun_ and _Shir HaMa'alos_. It's not always necessary, and it takes up a lot of space. I could add a `<details>` element for those. What do you think?

**Comment by akivajgordon** [comment]
My personal taste is for no collapsing, but I see your suggestion as a reasonable balance.

Alternate approach: use hebcal API (or similar?) to only show the relevant parts for that day, like not needing to show _Al hanisim_ most days. Perhaps an optional toggle somewhere to show everything regardless of the day (like someone who wants to refer to the text for _Al hanisim_ even when it's not Purim/Chanukah)

**Comment by binyamin** [comment]
@akivajgordon I made a fix on a different subdomain. Can you check it out on a phone, and see if you still prefer no collapsing? I couldn't decide on a UI with just two sections collapsible. https://bentcher-git-issue-1-binyamin.vercel.app/

**Comment by akivajgordon** [comment]
@binyamin I tried it out on both desktop and my phone. I totally love it. Super simple, no frills, just beautiful typography and the bentching that I need. This is gonna be a hit.
